version: '3.8'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: cars
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ./mysql:/var/lib/mysql