spring:
  application:
    name: Cars-API
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/cars
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration